### ISSUE TITLE
too many 500 error responses

### ISSUE THREAD

**Issue by luisgrisolia** [maread99/market_prices#248]
Hi there, I'm trying to test the library but I'm getting this error:
`RetryError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: [/v1/test/getcrumb](https://file+.vscode-resource.vscode-cdn.net/v1/test/getcrumb) (Caused by ResponseError('too many 500 error responses'))`

PD: it is the first run, other libraries (yfinance) are working as intended

Any hint?

**Comment by maread99** [comment]
Hi @luisgrisolia

Thanks for raising this. It's the `yahooquery` dependency. Apparently this issue has been fixed in the latest version.

Hopefully if you upgrade your yahooquery package to version 2.3.7 that should fix it.

If it doesn't then it may be because I need to change [this line](https://github.com/maread99/market_prices/blob/04c252fa03b9af2e2220163bf559cf15396c2721/src/market_prices/prices/yahoo.py#L360) to pass asynchronous as False. If you override that line in your locally installed version of `market_prices` then that should, according to recently closed issues over at [yahooquery](https://github.com/dpguthrie/yahooquery/issues?q=is%3Aissue+is%3Aclosed), do the trick.

I will make the change here, upgrade the dependencies and cut a new release, although probably not until after xmas now...

Let me know how you get on!
Cheers

**Comment by luisgrisolia** [comment]
HI @maread99 
I cloned the repo and created a clean local development environment and for my surprise it worked fine without further modifications. On the other hand, while creating a clean environment but instead installing the library using pypi I get the same error.

The versions of `urllib3, valimp and yahooquery` are outdated, that's the problem (dependabot is already into it as I noticed)

Thanks a lot for your help, and good work 🤓
Cheers

**Comment by maread99** [comment]
Good to hear it's all working.👍 

I'll update the dependencies shortly.

Let me know of any other issues you run into.

Cheers
